version: '3'

services:
  front-end:
    build:
      context: ./a1-front
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./a1-front:/usr/app
    stdin_open: true

  back-end:
    build:
      context: ./a2-back
      dockerfile: Dockerfile.dev
    ports:
      - 3001:3001
    volumes:
      - ./a2-back:/usr/app
    environment:
      GO_ENV: development